service: course-project-03
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:158626108575:table/ProductTable  

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  newItem:
    handler: src/newItem.handler
    events:
      - http:
          path: /item
          method: post
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put
  loadItem:
    handler: src/loadItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  loadItems:
    handler: src/loadItems.handler
    events:
      - http:
          path: /items
          method: get

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ProductTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          GlobalSecondaryIndexes:
            - IndexName: pk-table-items
              KeySchema:
                - AttributeName: id
                  KeyType: HASH
              Projection:
                ProjectionType: ALL